In [3]:
import numpy as np
import pandas as pd

matrix_a = np.asarray([
    [0.7, 3, 9],
    [1.7, 2, 9],
    [0.7, 9, 2]], dtype = float)

vector_b = np.asarray([
    [1],
    [2],
    [1]], dtype = float)

ab_product = np.dot(matrix_a, vector_b)
print(ab_product)

[[ 15.7]
 [ 14.7]
 [ 20.7]]


In [4]:
matrix_a = np.asarray([
    [0.7, 3],
    [1.7, 2],
    [0.7, 9]
], dtype=np.float32)

matrix_b = np.asarray([
    [113, 3, 10],
    [1, 0, 1],
], dtype=np.float32)

product_ab = np.dot(matrix_a, matrix_b)
product_ba = np.dot(matrix_b, matrix_a)

print(product_ab)
print(product_ba)

[[  82.09999847    2.0999999    10.        ]
 [ 194.1000061     5.10000038   19.        ]
 [  88.09999847    2.0999999    16.        ]]
[[  91.19999695  435.        ]
 [   1.39999998   12.        ]]


## np.transpose()

In [5]:
transpose_a = np.transpose(matrix_a)
print(np.transpose(transpose_a))

trans_ba = np.dot(np.transpose(matrix_b), np.transpose(matrix_a))
print(trans_ba)

trans_ab = np.dot(np.transpose(matrix_a), np.transpose(matrix_b))
print(trans_ab)

product_ab = np.dot(matrix_a, matrix_b)
print(np.transpose(product_ab))

[[ 0.69999999  3.        ]
 [ 1.70000005  2.        ]
 [ 0.69999999  9.        ]]
[[  82.09999847  194.1000061    88.09999847]
 [   2.0999999     5.10000038    2.0999999 ]
 [  10.           19.           16.        ]]
[[  91.19999695    1.39999998]
 [ 435.           12.        ]]
[[  82.09999847  194.1000061    88.09999847]
 [   2.0999999     5.10000038    2.0999999 ]
 [  10.           19.           16.        ]]


## np.identity()

In [6]:
i_2 = np.identity(2)
i_3 = np.identity(3)

matrix_33 = np.asarray([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

matrix_23 = np.asarray([
    [0.7, 3, 1],
    [1.7, 2, 10],
], dtype=np.float32)

identity_33 = np.dot(i_3, matrix_33)
identity_23 = np.dot(i_2, matrix_23)

print(identity_33)
print(identity_23)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]]
[[  0.69999999   3.           1.        ]
 [  1.70000005   2.          10.        ]]


In [7]:
matrix_a = np.asarray([
    [1.5, 3],
    [1, 4]
])
def matrix_inverse_two(mat):
    det = (mat[0,0]*mat[1,1] - mat[0,1]*mat[1,0])
    if det == 0:
        raise ValueError("The matrix isn't invertible")
    right_mat = np.asarray([
        [mat[1,1], -mat[0,1]],
        [-mat[1,0], mat[0,0]]
    ])
    inv_mat = np.dot(1/det, right_mat)
    return inv_mat
inverse_a = matrix_inverse_two(matrix_a)
i_2 = np.dot(inverse_a, matrix_a)
print(i_2)

[[ 1.  0.]
 [ 0.  1.]]


##  numpy.linalg.inv() 

In [8]:
matrix_a = np.asarray([
    [30, -1],
    [50, -1]
])

vector_b = np.asarray([
    [-1000],
    [-100]
])
matrix_a_inverse = np.linalg.inv(matrix_a)
solution_x = np.dot(matrix_a_inverse, vector_b)
print(solution_x)

[[   45.]
 [ 2350.]]


## numpy.linalg.det()

In [9]:
matrix_22 = np.asarray([
    [8, 4],
    [4, 2]
])

matrix_33 = np.asarray([
    [1, 1, 1],
    [1, 1, 6],
    [7, 8, 9]
])
det_22 = np.linalg.det(matrix_22)
det_33 = np.linalg.det(matrix_33)

print(det_22)
print(det_33)

0.0
-5.0
